// @ts-nocheck
/**
 * Base Video Template
 *
 * Copy this file as your starting point for any Remotion video.
 * Works with timing.json from generate_tts.py for audio sync.
 *
 * Usage:
 *   1. Copy to your project: cp templates/Video.tsx src/remotion/
 *   2. Import components from ./design/
 *   3. Customize sections based on your timing.json
 */

import { AbsoluteFill, Sequence, Audio, staticFile } from 'remotion'
import {
  // Layout
  FullBleed, ContentArea, CoverMedia,
  // Animation
  FadeIn, SpringPop,
  // Typography
  Title, Text, Caption,
  // Data
  DataDisplay,
  // UI
  Card,
  // Navigation
  ChapterProgressBar,
  // Tokens & Themes
  tokens, font, minimalWhite,
} from './design'

// Import timing data (generated by generate_tts.py)
import timing from '../../videos/your-video/timing.json'

// Types for timing.json
interface Section {
  name: string
  label?: string
  start_frame: number
  duration_frames: number
  is_silent?: boolean
}

interface Timing {
  total_frames: number
  fps: number
  sections: Section[]
}

const typedTiming = timing as Timing

// Helper to get section by name
const getSection = (name: string): Section | undefined =>
  typedTiming.sections.find(s => s.name === name)

// =============================================================================
// SECTION COMPONENTS
// =============================================================================

const HeroSection = () => (
  <FullBleed background={tokens.colors.bg}>
    <ContentArea verticalAlign="center">
      <FadeIn delay={0}>
        <Title size="hero">Your Title Here</Title>
      </FadeIn>
      <FadeIn delay={15}>
        <Title size="medium" style={{ color: tokens.colors.textMuted, marginTop: 24 }}>
          Your subtitle goes here
        </Title>
      </FadeIn>
    </ContentArea>
  </FullBleed>
)

const ContentSection = () => (
  <FullBleed background="#f8fafc">
    <ContentArea>
      <FadeIn delay={0}>
        <Title>Section Title</Title>
      </FadeIn>
      <FadeIn delay={20}>
        <Text style={{ marginTop: 32 }}>
          Your content goes here. Use FadeIn with staggered delays
          to create smooth animations.
        </Text>
      </FadeIn>
    </ContentArea>
  </FullBleed>
)

const DataSection = () => (
  <FullBleed background={tokens.colors.bg}>
    <ContentArea>
      <FadeIn delay={0}>
        <Title>Key Metrics</Title>
      </FadeIn>
      <div style={{
        display: 'flex',
        justifyContent: 'space-around',
        marginTop: 60,
      }}>
        {[
          { value: '1M+', label: 'Users' },
          { value: '99.9%', label: 'Uptime' },
          { value: '50ms', label: 'Latency' },
        ].map((item, i) => (
          <SpringPop key={i} delay={20 + i * 15}>
            <DataDisplay
              value={item.value}
              label={item.label}
              size="large"
            />
          </SpringPop>
        ))}
      </div>
    </ContentArea>
  </FullBleed>
)

const OutroSection = () => (
  <FullBleed background={tokens.colors.bg}>
    <ContentArea verticalAlign="center">
      <FadeIn delay={0}>
        <Title size="large" style={{ textAlign: 'center' }}>
          Thanks for Watching!
        </Title>
      </FadeIn>
      <FadeIn delay={20}>
        <div style={{
          display: 'flex',
          justifyContent: 'center',
          gap: 40,
          marginTop: 48,
        }}>
          <Card style={{ padding: '24px 48px' }}>
            <Text>👍 Like</Text>
          </Card>
          <Card style={{ padding: '24px 48px' }}>
            <Text>🔔 Subscribe</Text>
          </Card>
        </div>
      </FadeIn>
    </ContentArea>
  </FullBleed>
)

// =============================================================================
// MAIN VIDEO COMPOSITION
// =============================================================================

export const MyVideo = () => {
  const hero = getSection('hero')
  const content = getSection('content')
  const data = getSection('data')
  const outro = getSection('outro')

  return (
    <AbsoluteFill style={{
      fontFamily: font,
      background: tokens.colors.bg,
    }}>
      {/* 4K Scale Wrapper - design at 1080p, render at 4K */}
      <AbsoluteFill style={{
        transform: 'scale(2)',
        transformOrigin: 'top left',
        width: '50%',
        height: '50%',
      }}>
        {/* Audio Track */}
        <Audio src={staticFile('videos/your-video/podcast_audio.wav')} />

        {/* Chapter Progress Bar (optional) */}
        <ChapterProgressBar
          chapters={typedTiming.sections.map(s => ({
            name: s.name,
            label: s.label || s.name,
            start_frame: s.start_frame,
            duration_frames: s.duration_frames,
          }))}
          totalFrames={typedTiming.total_frames}
        />

        {/* Sections */}
        {hero && (
          <Sequence from={hero.start_frame} durationInFrames={hero.duration_frames}>
            <HeroSection />
          </Sequence>
        )}

        {content && (
          <Sequence from={content.start_frame} durationInFrames={content.duration_frames}>
            <ContentSection />
          </Sequence>
        )}

        {data && (
          <Sequence from={data.start_frame} durationInFrames={data.duration_frames}>
            <DataSection />
          </Sequence>
        )}

        {outro && (
          <Sequence from={outro.start_frame} durationInFrames={outro.duration_frames}>
            <OutroSection />
          </Sequence>
        )}
      </AbsoluteFill>
    </AbsoluteFill>
  )
}

export default MyVideo
